# Generated by Django 6.1.1 on 2026-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blinkit',
            fields=[
                ('Order_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=15)),
                ('Product_Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Mobile_No', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=15)),
                ('Address', models.TextField()),
            ],
        ),
    ]
